name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["bucklist-api CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --config cloud-build.yaml .
          gcloud run deploy my-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:$GITHUB_SHA --region us-central1 --platform managed --allow-unauthenticated
