name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["bucklist-api CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.1
        with:
          project: ${{ secrets.GCP_PROJECT_ID }}
          service-account-key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --config cloud-build.yaml .
          gcloud run deploy my-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:$GITHUB_SHA --region us-central1 --platform managed --allow-unauthenticated
